// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aqzvokkheupvzwfimgfl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxenZva2toZXVwdnp3ZmltZ2ZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4ODg3NTgsImV4cCI6MjA2ODQ2NDc1OH0.DyU_YNGZ6U93Pgayx4DnLgj-7cdeZMr07tf4wX3s-hs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});